/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.panel;

import Model.StatisticProduct;
import Model.StatisticReceipt;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class ReceiptStatisticPanel extends javax.swing.JPanel {

    /**
     * Creates new form Receiptpanel
     */
    public ReceiptStatisticPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPane = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        Table.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductID", "Product", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.setGridColor(new java.awt.Color(51, 51, 51));
        Table.setInheritsPopupMenu(true);
        Table.setRowHeight(50);
        Table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Table.setShowGrid(true);
        ScrollPane.setViewportView(Table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public void loadStatisticReceipts(ArrayList<StatisticReceipt> list1) {
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        // Xóa tất cả các hàng trong model trước khi load dữ liệu mới
        model.setRowCount(0);

//        // Thêm dữ liệu từ ArrayList vào model
        for (StatisticReceipt sr : list1) {
//            Object[] rowData = {sp.getProduct().getProductID(), sp.getProduct().getProductName(), sp.getQuanity(), sp.getIncome()};
//            model.addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTable Table;
    // End of variables declaration//GEN-END:variables
}
